config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create]
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"

  # Api
  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index show create destroy] do
        resources :posts, only: %i[index show create destroy] do
          resources :comments, only: %i[index show]
          resources :likes, only: %i[index show]
        end
      end
    end
  end
end

app/models/user.rb
# A user has many posts, comments, and likes.
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :postsCounter, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true },
                           allow_nil: true

  # Role-based authorization
  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end

  # A method to return a recent list of posts by this user
  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  # GET /api/v1/users
  def index
    @users = User.includes(posts: %i[comments author]).all.select(:id, :name, :photo, :email, :bio, :postsCounter)

    render json: @users
  end

  # GET /api/v1/users/:id
  def show
    @user = User.select(:id, :name, :photo, :email, :bio, :postsCounter).find(params[:id])
    render json: @user
  end

  # POST /api/v1/users
  def create
    @user = User.new(user_params)
    if @user.save
      render json: { status: :created, user: @user, notice: 'User was successfully created.', location: @user }
    else
      render json: { status: :unprocessable_entity, errors: @user.errors }
    end
  end

  # PATCH/PUT /api/v1/users/:id
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      render json: { status: :ok, user: @user, notice: 'User was successfully updated.', location: @user }
    else
      render json: { status: :unprocessable_entity, errors: @user.errors }
    end
  end

  # DELETE /api/v1/users/:id
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    render json: { status: :ok }
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(posts: %i[comments author]).all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/views/users/index.html.erb
<div class='users-container'>

<h1>List all Users</h1>

<div>
<% @users.each do |user| %>
    <div class= 'users-info'>
    <img src='<%= user.photo %>' alt = 'images' class= 'img' >
    
    <div class= user-list>
      <h2>
       <%= link_to user.name, user %>
      </h2>
     <p class= 'postscounter'>Number of Posts = <%=user.postsCounter %></p>
    </div>
    </div>
        <%= button_to "Log Out", destroy_user_session_path(user), method: :delete %> 
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class= 'post-info'>
<h1>User info</h1>
<div class= 'users-info'>
<img src="<%= @user.photo %>" alt="user photo" class="img">
<div class= user-list>
<h2><%= @user.name %></h2>
<p class= 'postscounter'>Number of Posts: <%= @user.postsCounter %></p>
</div>
</div>
<p>Bio:</p>
<p class= 'bio'> <%= @user.bio %></p>


<button class= 'btn'><%= link_to 'Posts', user_posts_path(@user) %></button>

<div>
    <% @user.recent_posts.each do |post| %>
        <h3 class='user-posts'> Post #<%= post.id %> <%= link_to post.title, user_post_path(@user, post) %>
        </h3>
        <p><%= post.text %> </p>
        <p class= 'user-comments-likes'>Comments: <%= post.commentsCounter %>, Likes: <%= post.likesCounter %></p>
    <% end %>

</div>
        <h2><%= link_to "New Post", new_user_post_path(@user) %></h2>
</div>

app/views/users/user.html.erb
<h1>List all Users</h1>

<ul>
<li>User 1</li>
<li>User 2</li>
<li>User 3</li>
<li>User 4</li>
<li>User 5</li>
<li>User 6</li>
<li>User 7</li>
<li>User 8</li>
<li>User 9</li>
</ul>