config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create]
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"

  # Api
  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index show create destroy] do
        resources :posts, only: %i[index show create destroy] do
          resources :comments, only: %i[index show]
          resources :likes, only: %i[index show]
        end
      end
    end
  end
end

app/models/post.rb
# Base class for models in the application.
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true, length: { minimum: 2, maximum: 1000 }
  validates :commentsCounter, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likesCounter, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  after_save :update_post_counter_cache
  after_destroy :update_post_counter_cache

  # A method to return a recent list of comments on this post
  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  # A method that updates the posts counter for a user.
  def update_post_counter_cache
    author.update(postsCounter: author.posts.count)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  # GET /api/v1/posts
  def index
    @posts = Post.includes(:author, :comments, :likes).all
    render json: @posts
  end

  # GET /api/v1/posts/:id
  def show
    @post = Post.find(params[:id])
    render json: @post
  end

  # POST /api/v1/posts
  def create
    @post = Post.new(post_params)
    if @post.save
      render json: { status: :created, post: @post, notice: 'Post was successfully created.', location: @post }
    else
      render json: { status: :unprocessable_entity, errors: @post.errors }
    end
  end

  # PATCH/PUT /api/v1/posts/:id
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      render json: { status: :ok, post: @post, notice: 'Post was successfully updated.', location: @post }
    else
      render json: { status: :unprocessable_entity, errors: @post.errors }
    end
  end

  # DELETE /api/v1/posts/:id
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    render json: { status: :ok }
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :author_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.includes(posts: %i[comments author]).find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to user_post_path(current_user.id, @post.id)
    else
      render :new
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    flash[:success] = 'Post was deleted successfully.'
    redirect_to user_posts_path(current_user.id, @post.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text).merge(author_id: current_user.id, commentsCounter: 0, likesCounter: 0)
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/views/posts/index.html.erb
<div class='post-index'>
<h1>All posts</h1>

<div class= 'users-info'>

<img src="<%= @user.photo %>" alt="user photo" class="img">

<div class= user-list>
<h2><%= @posts.first.author.name %></h2>
<p class= 'postscounter'>Number of Posts: <%= @posts.first.author.postsCounter %></p>
</div>
</div>

    <div>
        <% @posts.each do |post| %> 
                <h2>Post #<%= post.id %> <%= link_to post.title, user_post_path(user_id: post.author.id, id: post.id) %></h2>
                <p><%= post.text %></p>
                </h3>
                <p class= 'user-comments-likes'>Comments: <%= post.commentsCounter %>, Likes: <%= post.likesCounter %></p>
            <div class= 'comments'>
                <h3>Here are the Comments for this post</h3>

                <% post.recent_comments.each do |comment| %>
                <p><%= comment.author.name %>: <%= comment.text %></p>
                <% end %>
            </div>
            <% if can? :destroy, post %>
                <%= link_to "Delete Post", user_post_path(post.author.id, post.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn" %>
            <% end %>
        <% end %> <br>
        <h2>Pagination</h2><br>
       <h2> <%= link_to "New Post", new_user_post_path %></h2>

        <h2><%= link_to "Back to Users", users_path %> </h2>
                
    </div>
</div>

app/views/posts/new.html.erb
<div class='post-info'>
<h1>New Post</h1>

<%= form_with model: @post, url: user_posts_path(@user), local: true  do |form| %>
        <h3>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </h3>
    <h3>
        <%= form.label :text %><br>
        <%= form.text_area :text %>
    </h3>
    <h3>
        <%= form.submit %>
    </h3>
<% end %>
</div>

app/views/posts/show.html.erb
<div class='post-info'>
  <h1>User's post info</h1>

  <div class= 'users-info'>
    <img src="<%= @post.author.photo %>" alt="user photo" class="img">
    <div class= user-list>
      <h2><%= @post.author.name %></h2>
      <p class= 'postscounter'>Number of Posts: <%= @post.author.postsCounter %></p>
    </div>
  </div>


    <h3 class='user-posts'> Post #<%= @post.id %> <%= @post.title %> by <%= @post.author.name%> </h3>
  <p><%= @post.text %> </p>
  <p class= 'user-comments-likes'>Comments: <%= @post.commentsCounter %>, Likes: <%= @post.likesCounter %></p>
    

  <h3>Here is the Comments for this post</h3>
  <div class= 'comments'>
    <% @post.recent_comments.each do |comment| %>
      <p><%= comment.author.name %>: <%= comment.text %></p>
    <div class='delete-comments' > <% if can? :destroy, comment %>
        <%= link_to "Delete Comment", user_post_comment_path(@post.author.id, @post.id, comment.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn" %>
      <% end %></div> 
    <% end %>
  </div>
  <h2> <%= link_to "New Comment", new_user_post_comment_path(@user, @post) %> </h2>

<%= form_with model: @like, url: user_post_likes_path(@user, @post), local: true do |form| %>
    <h2><%= form.submit "Like" %></h2>
  <% end %>

  <h2> <%= link_to "Back to Posts", user_posts_path(@user) %> </h2>
</div>